"""
  BG_LAYOUT(; title::String = "Observatorio de Inflación",
               meta::D = Dict(),
               head_content::Union{AbstractString, Vector} = "",
               core_theme::Bool = true) where {D <: AbstractDict}

The background layout for the Inflation Observatory app.
"""
function BG_LAYOUT(;
        title::String = "Observatorio de Inflación",
        meta::D = Dict(),
        head_content::Union{AbstractString, Vector} = "",
        core_theme::Bool = true
    ) where {D <: AbstractDict}

    tags = Genie.Renderers.Html.for_each(x ->
        """<meta name="$(string(x.first))" content="$(string(x.second))">\n""",
        meta
    )

    return """
    <!DOCTYPE html>
    <html lang="es" class="scroll-smooth">
      <head>
        <meta charset="utf-8" />

        $tags
        <% Stipple.sesstoken() %>

        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/bg/logo_bg_0.png" type="image/png" />
        <title>$title</title>

        <% if isfile(joinpath(Stipple.Genie.config.server_document_root, "css", "genieapp.css")) %>
        <link rel="stylesheet" href="/css/genieapp.css" />
        <% else %>
        <% end %>

        <style>
          [v-cloak] { display: none; }
        </style>

        $(head_content isa AbstractString ? head_content : join(head_content, "\\n    "))
      </head>

      <body class="min-h-screen bg-white text-slate-900">
        <% partial(Renderer.filepath(joinpath("src", "ui", "layouts", "partials", "navbar.jl.html"))) %>

        <main>
          <% Stipple.page(model, partial = true, v__cloak = true, [Stipple.Genie.Renderer.Html.@yield], Stipple.@if(:isready); core_theme = $core_theme) %>
        </main>

        <% partial(Renderer.filepath(joinpath("src", "ui", "layouts", "partials", "footer.jl.html"))) %>

        <% if isfile(joinpath(Stipple.Genie.config.server_document_root, "js", "genieapp.js")) %>
        <script src="/js/genieapp.js"></script>
        <% else %>
        <% end %>

        <% if isfile(joinpath(Stipple.Genie.config.server_document_root, "css", "autogenerated.css")) %>
        <link rel="stylesheet" href="/css/autogenerated.css" />
        <% else %>
        <% end %>

        <script src="https://cdn.tailwindcss.com"></script>
      </body>
    </html>
    """
end
